export const categories = [
  {
    id: 1,
    slug: "haircut",
    label: "Haircut",
    pathdark: "/assets/dark-catogories-avatar.svg",
    bannerimg: "/assets/haircut.svg",
    bannerdesc: "Get a stylish haircut!",
    offerDesc: "Earn 5 care coins on each haircut",
    backgroundColor: "#eeebf1",
    offerBoxColor: "#2e2e2e",
    offerTextColor: "#fff",
    services: [
      {
        id: 1,
        label: "Classic Haircut",
        desc: "A traditional haircut for a timeless look.",
        time: 45,
        ratings: 4.5,
        reviews: 198,
        prize: 30,
      },
      {
        id: 2,
        label: "Layered Haircut",
        desc: "Add depth and style to your hair with a layered cut.",
        time: 45,
        ratings: 4.2,
        reviews: 215,
        prize: 35,
      },
      {
        id: 3,
        label: "Beard Trim",
        desc: "Maintain your beard with a professional trim.",
        time: 20,
        ratings: 4.7,
        reviews: 150,
        prize: 15,
      },
    ],
  },
  {
    id: 2,
    slug: "facial",
    label: "Facial",
    pathdark: "/assets/dark-catogories-avatar.svg",
    bannerimg: "/assets/makeup.svg",
    bannerdesc: "Revitalize your skin with a refreshing facial!",
    offerDesc: "Get 10 care coins on each facial appointment",
    backgroundColor: "#f5f5f5",
    offerBoxColor: "#0a83e4",
    offerTextColor: "#fff",
    services: [
      {
        id: 1,
        label: "Basic Facial",
        desc: "A relaxing facial treatment to cleanse and hydrate your skin.",
        time: 60,
        ratings: 4.8,
        reviews: 250,
        prize: 50,
      },
      {
        id: 2,
        label: "Anti-Aging Facial",
        desc: "Reduce the signs of aging and rejuvenate your skin.",
        time: 75,
        ratings: 4.9,
        reviews: 280,
        prize: 75,
      },
    ],
  },
  {
    id: 3,
    slug: "nail-care",
    label: "Nail Care",
    pathdark: "/assets/dark-catogories-avatar.svg",
    bannerimg: "/assets/others.svg",
    bannerdesc: "Pamper yourself with a manicure or pedicure!",
    offerDesc: "Receive a free nail art session with each appointment",
    backgroundColor: "#fff",
    offerBoxColor: "#e44d26",
    offerTextColor: "#fff",
    services: [
      {
        id: 1,
        label: "Manicure",
        desc: "Treat your hands with a relaxing manicure session.",
        time: 30,
        ratings: 4.7,
        reviews: 120,
        prize: 25,
      },
      {
        id: 2,
        label: "Pedicure",
        desc: "Give your feet the care they deserve with a pedicure.",
        time: 40,
        ratings: 4.6,
        reviews: 135,
        prize: 30,
      },
    ],
  },
];
