import { useEffect } from "react";
import Head from "next/head";

import HomePageLayout from "../layout/client/HomePageLayout";
import Home from "../components/Home";
import { useRouter } from "next/router";

export default function HomePage() {
  const router = useRouter();
  useEffect(() => {
    router.replace("/holi-2024");
  }, []);

  return (
    <>
      <Head>
        <title>Pamprazzi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePageLayout>
          <Home />
        </HomePageLayout>
      </main>
    </>
  );
}
