import Head from "next/head";
import ShopListingPage from "../components/ShopListingPage";
import HomePageLayout from "../layout/client/HomePageLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pamprazzi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePageLayout>
          <ShopListingPage />
        </HomePageLayout>
      </main>
    </>
  );
}
